version: '3'

services:
  app:
    image: 'tmvdl/projects:antify'
    build: './src/app'
    volumes:
      - './src/app:/app'
    ports:
      - '8080:80'

  release:
    image: release
    volumes:
      - './src:/app'
    build: './src'

