version: '3'

services:

  app:
    image: 'tmvdl/projects:antify'
    build: './src/app'
    volumes:
      - './src/app:/go/src/github.com/brtmvdl/antify'
    ports:
      - '555:555'

  github-release:
    image: 'github-release'
    build: './src/app'
