name: GitHub release

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Create tool manifest
        run: docker-compose run app dotnet new tool-manifest --force # https://www.nuget.org/packages/dotnet-deb

      - name: Running tool install
        run: docker-compose run app dotnet tool install --local dotnet-deb --version 0.1.226 # https://github.com/quamotion/dotnet-packaging

      - name: Running deb install
        run: docker-compose run app dotnet deb install

      - name: Create .deb file
        run: docker-compose run app dotnet deb --configuration Release

      - name: Create release
        run: gh release create v$( date +%Y%m%d%H%M ) ./src/dotnet/bin/Release/net8.0/app.1.0.0.deb
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
